# library(devtools)
# packageVersion("devtools")
# library(roxygen2)

#RNAseq packages needed
#library(Glimma)
#library(edgeR)
# library(biomaRt)
# library(DESeq2)
# library(ashr)
# library(org.Mm.eg.db)
# library(ggridges)
# library(ggplot2)
# library(ggrepel)
# library(gtable)
# library(scales)
# library(grid)
# library(RColorBrewer)
# library(ggpubr)
# library(uwot)
# library(VennDiagram)
# library(pheatmap)
# library(clusterProfiler)
# library(treemap)
# library(DOSE)
# library(pathview)
# library(utils)
# library(stringi)
# library(stringr)
# library(knitr)
# library(rmarkdown)
# library(ReportingTools)
# library(tidyverse)
# library(tinytex)
#
# devtools::install_github('JamesJoly/DGSEA')
# devtools::install_github('analyzeRNAseq', 'amcass')
